Migrating test_add_identical_brick_new_node.py (#604)
* Add identical brick on new node after down a brick on other node

1. Create Dist Volume on Node 1
2. Down brick on Node 1
3. Peer Probe N2 from N1
4. Add identical brick on newly added node
5. Check volume status

Change-Id: I17c4769df6e4ec2f11b7d948ca48a006cf301073
Signed-off-by: Mohit Agrawal <moagrawa@redhat.com>

* Fix for test_add_identical_brick_new_node.py

Change-Id: Ic60e9da0a97818cba59b5be5048492e54fc0edb3
Signed-off-by: Sri <sselvan@redhat.com>

* Add py3 support in 'tests/functional/glusterd'. Part 1

Change-Id: Ib414b8496ca65a48bbe42936e32a863c9c1072e4
Signed-off-by: Valerii Ponomarov <kiparis.kh@gmail.com>

* Fixing a bunch of python3 incompatibilities

Problem:
There are two python2 to python3 incompatibilities
present in test_add_brick_when_quorum_not_met.py
and test_add_identical_brick_new_node.py.

In test_add_brick_when_quorum_not_met.py the testcase
fails with the below error:

> for node in range(num_of_nodes_to_bring_down, num_of_servers):
E TypeError: 'float' object cannot be interpreted as an integer

This is because a = 10 / 5 returns a float in python3
but it returns a int in python2 as shown below:

Python 2.7.15 (default, Oct 15 2018, 15:26:09)
[GCC 8.2.1 20180801 (Red Hat 8.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 10/5
>>> type(a)
<type 'int'>

Python 3.7.3 (default, Mar 27 2019, 13:41:07)
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 10/5
>>> type(a)
<class 'float'>

In test_add_identical_brick_new_node.py testcase
fails with the below error:
> add_bricks.append(string.replace(bricks_list[0],
                    self.servers[0], self.servers[1]))
E AttributeError: module 'string' has no attribute 'replace'

This is because string is depriciated in python3 and
is replaced with str.

Solution:
For the first issue we would need to change
a = 10/5 to a = 10//5 as it is constant
across both python versions.

For the second issue adding try except
block as shown below would be suffice:
except AttributeError:
       add_bricks.append(str.replace(bricks_list[0],
                                     self.servers[0],
                                     self.servers[1]))

Change-Id: I9ec325760b279032af3748101bd2bfc58589d57d
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Migrating test_add_identical_brick_new_node.py

Updates: #292
Fixes: #598
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

* redundant ret values are removed and peer_probe_servers is called with
validate option

Fixes: #598
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

* checking peer_probe for None and checking bricks_list for None

Fixes: #598
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

Co-authored-by: Mohit Agrawal <moagrawa@redhat.com>
Co-authored-by: Sri <sselvan@redhat.com>
Co-authored-by: Valerii Ponomarov <vponomar@redhat.com>
Co-authored-by: kshithijiyer <kshithij.ki@gmail.com>