Migrated TC test_snap_delete_multiple (#1010)
* Snapshot: Delete Multiple snapshots of volumes simultaneously

Delete multiple snapshots of the original and cloned volumes
simultaneously.

Change-Id: Ic5165b896d2adf4cb51ad4252b7caad7bb6f0892
Signed-off-by: srivickynesh <sselvan@redhat.com>
Signed-off-by: Sri <sselvan@redhat.com>

* Add py3 support in 'tests/functional/snapshot'

Change-Id: Ie408d7972452123b63eb5cc17c61bc319a99e304
Signed-off-by: Valerii Ponomarov <kiparis.kh@gmail.com>

* Remove variable script_local_path(Part 1)

Removing script_local_path as both script_local_path and
cls.script_upload_path hold the same values which makes
each script slow. This will help decrease the execution
time of the test suite.

PoC:
$cat test.py
a = ("/usr/share/glustolibs/io/scripts/"
     "file_dir_ops.py")
b = ("/usr/share/glustolibs/io/scripts/"
     "file_dir_ops.py")
$time python test.py

real 0m0.063s
user 0m0.039s
sys  0m0.019s

$cat test.py
a = ("/usr/share/glustolibs/io/scripts/"
     "file_dir_ops.py")
$time python test.py

real 0m0.013s
user 0m0.009s
sys  0m0.003s

Code changes needed:

From:
script_local_path = ("/usr/share/glustolibs/io/scripts/"
                     "file_dir_ops.py")
cls.script_upload_path = ("/usr/share/glustolibs/io/scripts/"
                          "file_dir_ops.py")
ret = upload_scripts(cls.clients, script_local_path)

To:
cls.script_upload_path = ("/usr/share/glustolibs/io/scripts/"
                          "file_dir_ops.py")
ret = upload_scripts(cls.clients, cls.script_upload_path)

Change-Id: I7908b3b418bbc929b7cc3ff81e3675310eecdbeb
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Add steps to stabilize contents in snapshot - part2

used library functions to wait for glusterd to start
and wait for peer to connect and made modifications in teardown part
to rectified statements to correct values

Change-Id: I40b4362ae1491acf75681c7623c16c53213bb1b9
Signed-off-by: Sri Vignesh <sselvan@redhat.com>

* Remove python version dependency(Part 5)

Please refer to commit message of patch [1].

[1] https://review.gluster.org/#/c/glusto-tests/+/24140/

Change-Id: I5319ce497ca3359e0e7dbd9ece481bada1ee2205
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Fix I/O of test_snap_delete_multiple

Problem:
test_snap_delete_multiple fails on I/O validation across all automation
runs constantly with the below trace back:
Traceback (most recent call last):
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 1246, in <module>
    rc = args.func(args)
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 374, in create_files
    base_file_name, file_types)
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 341, in _create_files
    ret = pool.map(lambda file_tuple: _create_file(*file_tuple), files)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
IOError: [Errno 17] File exists: '/mnt/testvol_distributed_glusterfs/testfile42.txt'

Fix:
Change the I/O to use --base-file-name parameter when running the I/O
scripts.

Change-Id: Ic5a8222f4fafeac4ac9aadc9c4d23327711ed9f0
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Migrated TC test_snap_delete_multiple

Signed-off-by: nik-redhat <nladha@redhat.com>

* Fix object name

Signed-off-by: nik-redhat <nladha@redhat.com>

* Make mounts dict list

Signed-off-by: nik-redhat <nladha@redhat.com>

* Mart the TC as excluded

Signed-off-by: nik-redhat <nladha@redhat.com>

Co-authored-by: srivickynesh <sselvan@redhat.com>
Co-authored-by: Valerii Ponomarov <vponomar@redhat.com>
Co-authored-by: kshithijiyer <kshithij.ki@gmail.com>