Migrated TC test_mount_snap (#1025)
* Snapshot: Testcase to validate snapshot mount

Change-Id: I3af948e10673737d06e352e3bb8a1bec58ea3c55
Signed-off-by: srivickynesh <sselvan@redhat.com>

* Shorten all the logs around verify_io_procs

No functional change, just make the tests a bit more readable.
It could be moved to a decorator later on, wrapping tests.

Change-Id: I484bb8b46907ee8f33dfcf4c960737a21819cd6a
Signed-off-by: Yaniv Kaul <ykaul@redhat.com>

* Fix spelling mistake across the codebase

Change-Id: I46fc2feffe6443af6913785d67bf310838532421

* Add py3 support in 'tests/functional/snapshot'

Change-Id: Ie408d7972452123b63eb5cc17c61bc319a99e304
Signed-off-by: Valerii Ponomarov <kiparis.kh@gmail.com>

* Remove variable script_local_path(Part 1)

Removing script_local_path as both script_local_path and
cls.script_upload_path hold the same values which makes
each script slow. This will help decrease the execution
time of the test suite.

PoC:
$cat test.py
a = ("/usr/share/glustolibs/io/scripts/"
     "file_dir_ops.py")
b = ("/usr/share/glustolibs/io/scripts/"
     "file_dir_ops.py")
$time python test.py

real 0m0.063s
user 0m0.039s
sys  0m0.019s

$cat test.py
a = ("/usr/share/glustolibs/io/scripts/"
     "file_dir_ops.py")
$time python test.py

real 0m0.013s
user 0m0.009s
sys  0m0.003s

Code changes needed:

From:
script_local_path = ("/usr/share/glustolibs/io/scripts/"
                     "file_dir_ops.py")
cls.script_upload_path = ("/usr/share/glustolibs/io/scripts/"
                          "file_dir_ops.py")
ret = upload_scripts(cls.clients, script_local_path)

To:
cls.script_upload_path = ("/usr/share/glustolibs/io/scripts/"
                          "file_dir_ops.py")
ret = upload_scripts(cls.clients, cls.script_upload_path)

Change-Id: I7908b3b418bbc929b7cc3ff81e3675310eecdbeb
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Remove python version dependency(Part 5)

Please refer to commit message of patch [1].

[1] https://review.gluster.org/#/c/glusto-tests/+/24140/

Change-Id: I5319ce497ca3359e0e7dbd9ece481bada1ee2205
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Fix I/O logic to use distinct file names

Problem:
Testcases test_mount_snap_delete and test_restore_online_vol
were failing in the latest runs with the below traceback
```
Traceback (most recent call last):
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 1246, in <module>
    rc = args.func(args)
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 374, in create_files
    base_file_name, file_types)
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 341, in _create_files
    ret = pool.map(lambda file_tuple: _create_file(*file_tuple), files)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 341, in <lambda>
    ret = pool.map(lambda file_tuple: _create_file(*file_tuple), files)
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 270, in _create_file
    with open(file_abs_path, "w+") as new_file:
FileExistsError: [Errno 17] File exists: '/mnt/testvol_distributed_glusterfs/file1.txt'
```
This was because I/O logic was trying to create 2 files with the same
name from 2 clients.

Fix:
Modify logic to use counters to create files with different names.

Change-Id: I2896736d28f6bd17435f941088fd634347e3f4fd
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Migrated TC test_mount_snap

Signed-off-by: nik-redhat <nladha@redhat.com>

Co-authored-by: srivickynesh <sselvan@redhat.com>
Co-authored-by: Yaniv Kaul <ykaul@redhat.com>
Co-authored-by: Nigel Babu <nigelb@redhat.com>
Co-authored-by: Valerii Ponomarov <vponomar@redhat.com>
Co-authored-by: kshithijiyer <kshithij.ki@gmail.com>