Migrate TC test_volume_start_stop_while_rebalance_in_progress.py (#1150)
* Rebalance: starting and stopping the volume while rebalance is in progress

This testcase verifies, volume stop should not be allowed while
rebalance is in-progress and it should throw appropriate error.

Change-Id: I24ffc263f26eb99fff774cb851ac98ac6fed2bee
Signed-off-by: Prasad Desala <tdesala@redhat.com>

* Add py3 support in 'tests/functional/dht'

Change-Id: I44fe85519c8fd381064670e54dac8736107b0928
Signed-off-by: Valerii Ponomarov <kiparis.kh@gmail.com>

* Remove variable script_local_path(Part 2)

Please refer to the commit message of the below patch:
https://review.gluster.org/#/c/glusto-tests/+/23902/

Change-Id: I0d2eeb978c6757d6d910ebfe21b07811bf74b80a
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Remove python version dependency(Part 4)

Please refer to commit message of patch [1].

[1] https://review.gluster.org/#/c/glusto-tests/+/24140/

Change-Id: I25d30f7bdb20f0825709c4c852140e1906870ce7
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Fix logging error

Problem:
Line 135 is missing () which leads to the below trace back
when the testcase fails:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file test_volume_start_stop_while_rebalance_in_progress.py, line 135
```

Solution:
Adding the missing () brackets in line 135.

Change-Id: I318a5b838f01840afee5d4109645cc7dcd86c8fa
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Moving test steps from teardown class to teardown

Move cases from teardown class to teardown in dht

Change-Id: Id0cf120c6229715521ae19fd4bb00cad553d701f
Signed-off-by: Sri Vignesh <sselvan@redhat.com>

* Change g.log.error() to self.assertTrue()

Problem:
Testcases test_volume_start_stop_while_rebalance_is_in_progress throws
the below traceback when run:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file test_volume_start_stop_while_rebalance_in_progress.py, line 135
```
This is because g.log.error() was used instead of
self.assertTrue().

Solution:
Changing to self.assertTrue().

Change-Id: If926eb834c0128a4e507da9fdd805916196432cb
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Migrate TC test_volume_start_stop_while_rebalance_in_progress.py

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

Co-authored-by: Prasad Desala <tdesala@redhat.com>
Co-authored-by: Valerii Ponomarov <vponomar@redhat.com>
Co-authored-by: kshithijiyer <kshithij.ki@gmail.com>
Co-authored-by: Sri Vignesh <sselvan@redhat.com>