Migrated TC test_ec_truncate_file_with_brick_down (#1061)
* Truncate a file with brick down

Test steps:
1. Create a volume, start and mount it on a client
2. Bring down redundant bricks in the subvol
3. Create a file on the volume using "touch"
4. Truncate the file using "O_TRUNC"
5. Bring the brick online
6. Write data on the file and wait for heal completion
7. Check for crashes and coredumps

Change-Id: Ie02a56ab5180f6a88e4499c8cf6e5fe5019e8df1
Signed-off-by: Bala Konda Reddy M <bala12352@gmail.com>

* Fix TypeError for python3

Problem: Test is failing with below traceback
when ran with python3 as default.
`
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
`
Solution:
Added ''.encode() which will fix the issue when ran
using both python2 and python3

Added a check for core file on the client node.

Change-Id: I8f800f5fad97c3b7591db79ea51203e5293a1f69
Signed-off-by: Bala Konda Reddy M <bala12352@gmail.com>

* Add node restart validation

Extending the existing validation by adding
node restart as a method to bring back
offline bricks along with exiting volume start
approach.

Change-Id: I1291b7d9b4a3c299859175b4cdcd2952339c48a4
Signed-off-by: Pranav <prprakas@redhat.com>

* Migrated TC test_ec_truncate_file_with_brick_down

Signed-off-by: nik-redhat <nladha@redhat.com>

* Fix os.open() args

Signed-off-by: nik-redhat <nladha@redhat.com>

Co-authored-by: Bala Konda Reddy M <bala12352@gmail.com>
Co-authored-by: Pranav <prprakas@redhat.com>