Fix error in logging
Problem:
Testcase test_ec_version was failing with the
below traceback:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Logged from file test_ec_version_healing_whenonebrickdown.py, line 233

This was due to a missing 's' in the log message on line 233.

Solution:
Add the missing s in the log message on line 233 as
shown below:
g.log.info('Brick %s is offline successfully', brick_b2_down)

Also renaming the file for more clarity of what the
testcase does.

Change-Id: I626fbe23dfaab0dd6d77c75329664a81a120c638
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>