Change g.log.error() to self.assertTrue()
Problem:
Testcases test_volume_start_stop_while_rebalance_is_in_progress throws
the below traceback when run:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib64/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file test_volume_start_stop_while_rebalance_in_progress.py, line 135
```
This is because g.log.error() was used instead of
self.assertTrue().

Solution:
Changing to self.assertTrue().

Change-Id: If926eb834c0128a4e507da9fdd805916196432cb
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>