Migrated test_add_brick_when_quorum_not_met (#413)
* glusto-tests/glusterd: add brick should fail, when server quorum is not met

Steps followed are:
1. Create and a start a volume
2. Set cluster.server-quorum-type as server
3. Set cluster.server-quorum-ratio as 95%
4. Bring down glusterd in half of the nodes
5. Confirm that quorum is not met, by check whether the bricks are down.
6. Perform a add brick operation, which should fail.
7. Check whether added brick is part of volume.

Change-Id: I93e3676273bbdddad4d4920c46640e60c7875964
Signed-off-by: Sanju Rakonde <srakonde@redhat.com>

* Fix for test_add_brick_when_quorum_not_met.py

Change-Id: If8d18cd60d1993ce46fa019b659770cf6e7aa6b8
Signed-off-by: Sri <sselvan@redhat.com>

* Fixed jira issue RHGSQE-29 and added quorum reset code

Change-Id: Ibd50170d2c3172d7b98c2174630d31a066762f7c
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Add py3 support in 'tests/functional/glusterd'. Part 1

Change-Id: Ib414b8496ca65a48bbe42936e32a863c9c1072e4
Signed-off-by: Valerii Ponomarov <kiparis.kh@gmail.com>

* Add steps to add peer_probe_servers in cleanup

Change-Id: I0fa6bbacda16fb97d3454a8510a937442b5755a4
Signed-off-by: Sri Vignesh <sselvan@redhat.com>

* Fixing a bunch of python3 incompatibilities

Problem:
There are two python2 to python3 incompatibilities
present in test_add_brick_when_quorum_not_met.py
and test_add_identical_brick_new_node.py.

In test_add_brick_when_quorum_not_met.py the testcase
fails with the below error:

> for node in range(num_of_nodes_to_bring_down, num_of_servers):
E TypeError: 'float' object cannot be interpreted as an integer

This is because a = 10 / 5 returns a float in python3
but it returns a int in python2 as shown below:

Python 2.7.15 (default, Oct 15 2018, 15:26:09)
[GCC 8.2.1 20180801 (Red Hat 8.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 10/5
>>> type(a)
<type 'int'>

Python 3.7.3 (default, Mar 27 2019, 13:41:07)
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 10/5
>>> type(a)
<class 'float'>

In test_add_identical_brick_new_node.py testcase
fails with the below error:
> add_bricks.append(string.replace(bricks_list[0],
                    self.servers[0], self.servers[1]))
E AttributeError: module 'string' has no attribute 'replace'

This is because string is depriciated in python3 and
is replaced with str.

Solution:
For the first issue we would need to change
a = 10/5 to a = 10//5 as it is constant
across both python versions.

For the second issue adding try except
block as shown below would be suffice:
except AttributeError:
       add_bricks.append(str.replace(bricks_list[0],
                                     self.servers[0],
                                     self.servers[1]))

Change-Id: I9ec325760b279032af3748101bd2bfc58589d57d
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Adding cluster options reset in TC

The cluster options are reset post the TC run
so that they don't persist through the other
TC runs.

Change-Id: Id55bb64ded09e113cdc0fc512a17857195619e41
Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

* Migrated test_add_brick_when_quorum_not_met

Migrated the test case.
Added `are_bricks_offline` in brick ops.

Updates: #292

Fixes: #352

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* added doc about are_bricks_offline

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* modified the logic in are_bricks_offline

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* modified the doc

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* log modifications

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* added strict flag

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* added todo; rebased and removed the conflicts

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* Added wait_for_glusterd in place of sleep(15)

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* changed the message

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* removed sleep

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* modified the logic of are_bricks_offline

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* added the function in environ and calling from inside other ops

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* added function to check if bricks list changed

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

* added docs for the added functions

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

Co-authored-by: Sanju Rakonde <srakonde@redhat.com>
Co-authored-by: Sri <sselvan@redhat.com>
Co-authored-by: kshithijiyer <kshithij.ki@gmail.com>
Co-authored-by: Valerii Ponomarov <vponomar@redhat.com>
Co-authored-by: srijan-sivakumar <ssivakum@redhat.com>