Migrate TC test_stop_glusterd_while_rebalance_in_progress.py (#1107)
* Adding DHT test case: stop glusterd while rebalance in progress

Rebalance should proceed even if glusterd is down on a node.

Change-Id: I499e8a4e6b42bd7a8153c1d82c8b329a1933e748
Signed-off-by: Prasad Desala <tdesala@redhat.com>

* Fix spelling mistake across the codebase

Change-Id: I46fc2feffe6443af6913785d67bf310838532421

* Add py3 support in 'tests/functional/dht'

Change-Id: I44fe85519c8fd381064670e54dac8736107b0928
Signed-off-by: Valerii Ponomarov <kiparis.kh@gmail.com>

* Remove variable script_local_path(Part 2)

Please refer to the commit message of the below patch:
https://review.gluster.org/#/c/glusto-tests/+/23902/

Change-Id: I0d2eeb978c6757d6d910ebfe21b07811bf74b80a
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Remove python version dependency(Part 4)

Please refer to commit message of patch [1].

[1] https://review.gluster.org/#/c/glusto-tests/+/24140/

Change-Id: I25d30f7bdb20f0825709c4c852140e1906870ce7
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Moving test steps from teardown class to teardown

Move cases from teardown class to teardown in dht

Change-Id: Id0cf120c6229715521ae19fd4bb00cad553d701f
Signed-off-by: Sri Vignesh <sselvan@redhat.com>

* Increase timeouts and fix I/O errors

Problem:
--------

Problem 1:
In the latest runs the following testcases fail
with wait timeout mostly on rebalance with an exception
on test_stack_overflow which fails on layout:
1.functional.dht.test_stack_overflow.TestStackOverflow_cplex_dispersed_glusterfs.test_stack_overflow
2.functional.dht.test_rebalance_dir_file_from_multiple_clients.RebalanceValidation_cplex_dispersed_glusterfs.test_expanding_volume_when_io_in_progress
3.functional.dht.test_restart_glusterd_after_rebalance.RebalanceValidation_cplex_dispersed_glusterfs.test_restart_glusterd_after_rebalance
4.functional.dht.test_stop_glusterd_while_rebalance_in_progress.RebalanceValidation_cplex_dispersed_glusterfs.test_stop_glusterd_while_rebalance_in_progress
5.functional.dht.test_rebalance_with_hidden_files.RebalanceValidation_cplex_dispersed_glusterfs.test_rebalance_with_hidden_files

This is mostly observed on disprese volumes which
is expected as in most cases disprese volumes take
more time than pure replicated or distributed volumes
due to it's design.

Problem 2:
Another issue which was observed was that
test_rebalance_with_hidden_files failing on I/O with
distributed volume type with the below stack trace:

Traceback (most recent call last):
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 1246, in <module>
    rc = args.func(args)
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 374, in create_files
    base_file_name, file_types)
  File "/usr/share/glustolibs/io/scripts/file_dir_ops.py", line 341, in _create_files
    ret = pool.map(lambda file_tuple: _create_file(*file_tuple), files)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
IOError: [Errno 17] File exists: '/mnt/testvol_distributed_glusterfs/.1.txt'

Solution:
--------

Problem 1
Increasing or adding timeout so that wait timeouts are not observed.

Problem 2
Adding counter logic to fix the I/O failure.

Change-Id: I917137abdeb2e3844ee666258235f6ccc854ee9f
Signed-off-by: kshithijiyer <kshithij.ki@gmail.com>

* Migrate TC test_stop_glusterd_while_rebalance_in_progress.py

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

Co-authored-by: Prasad Desala <tdesala@redhat.com>
Co-authored-by: Nigel Babu <nigelb@redhat.com>
Co-authored-by: Valerii Ponomarov <vponomar@redhat.com>
Co-authored-by: kshithijiyer <kshithij.ki@gmail.com>
Co-authored-by: Sri Vignesh <sselvan@redhat.com>